### ISSUE TITLE
Does this work with dbt-cloud?

### ISSUE THREAD

**Issue by bolkedebruin** [getindata/dbt-airflow-factory#66]
Hi there!

We (Astronomer) we would like to cross-link to this project and were wondering if this project also works with dbt-cloud? :-)

Thanks!

**Comment by p-pekala** [comment]
Hi Bolkedebrin,

Thank you for your interest in the project. To be honest we haven't used it with dbt cloud yet as it gives the best experience and flexibility with another tool: https://github.com/getindata/data-pipelines-cli together with dbt core. But assuming usage dbt cloud just like an editor and moving the whole execution to Airflow there shouldn't be any problem with using this plugin. I would suggest the following approach:
- Use dbt cloud to create projects and edit models.
- Add extra yaml configuration that is required by dbt-airflow-factory
- Commit code to a git repository
- Create an appropriate CICD process that gathers and deploys artifacts (manifest.json and config files) to airflow.

Does it feet your needs?
